{ config
, pkgs
, ...
}: {
  imports = [
    ./appindicator
    ./autofirma
    ./bash
    ./computer-use-linux
    ./configuradorfnmt
    ./discord
    ./elvish
    ./factorio
    ./gcloud
    ./gimp
    ./gnome
    ./gnome-browser-connector
    ./gnome-firmware
    ./gnome-network-displays
    ./gnome-power-manager
    ./gnome-tweaks
    ./gsconnect
    ./helvum
    ./imapsync
    ./jadx
    ./jetbrains
    ./logseq
    ./masterpdfeditor
    ./meld
    ./notification-timeout
    ./nvtop
    ./panel-date-format
    ./pcon-planner
    ./piper-tts
    ./ringboard
    ./slack
    ./sox
    ./spotify
    ./starship
    ./system-monitor
    ./tailscale-status
    ./telegram-desktop
    ./theclicker
    ./tmux
    ./transmission-remote-gtk
    ./transmission_4-gtk
    ./txomon-android
    ./txomon-claude
    ./txomon-codex
    ./txomon-docker
    ./txomon-egpu
    ./txomon-gh
    ./txomon-git
    ./txomon-graphical
    ./txomon-kube
    ./txomon-notify
    ./vanta-agent
    ./vim
    ./vlc
    ./wine
    ./winetricks
    ./xdotool
    ./yq
  ];
}
